In [1]:
import numpy as np

In [3]:
#create a rank 1 array
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [5]:
#create a rank 2 array
arr2 = np.array([[1,2,3],
                [2,6,7]])
print(arr2)

[[1 2 3]
 [2 6 7]]


In [7]:
 # Creating an array from tuple
arr = np.array((1,2,3))
print(arr)

[1 2 3]
